"""
Layer 7 integration checkpoint — requires live Docker services.

Verifies (against real DB and Redis):
  (4) trade row is written to DB after on_fill()
  Integration of submit_order() → on_fill() end-to-end with MockBroker

Points (1)–(3) and (5) are fully covered by unit tests in
tests/unit/execution/test_order_manager.py.

Run after:
    docker-compose up -d
    docker-compose exec backend alembic upgrade head

Then:
    docker-compose exec backend pytest tests/integration/test_layer7_checkpoint.py -v
"""

import json
import os
import uuid
from decimal import Decimal

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.brokers.mock.client import MockBroker
from app.core.execution.order_manager import OrderManager
from app.core.execution.trade_handler import TRADE_EVENTS_CHANNEL, TradeHandler
from app.core.risk.manager import RiskManager, RiskRejectionError, TradeRequest
from app.data.cache import RedisCache
from app.db.repositories.trade_repo import TradeRepo

_DB_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql+asyncpg://trading:trading@localhost:5432/trading_bot",
)
_REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest_asyncio.fixture
async def broker() -> MockBroker:
    b = MockBroker()
    await b.connect()
    yield b
    await b.disconnect()


@pytest_asyncio.fixture
async def cache() -> RedisCache:
    c = RedisCache(_REDIS_URL)
    yield c
    await c.close()


@pytest_asyncio.fixture
async def session() -> AsyncSession:
    engine = create_async_engine(_DB_URL, echo=False)
    factory = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    async with factory() as sess:
        yield sess
        await sess.rollback()
    await engine.dispose()


def _valid_request(**kwargs) -> TradeRequest:
    defaults = {
        "trade_id": uuid.uuid4(),
        "symbol": "AAPL",
        "direction": "BUY",
        "quantity": Decimal("10"),
        "entry_price": Decimal("200"),
        "stop_loss_price": Decimal("195"),
        "account_balance": Decimal("100000"),
    }
    defaults.update(kwargs)
    return TradeRequest(**defaults)


# ---------------------------------------------------------------------------
# Checkpoint (4): trade row written to DB
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_on_fill_persists_trade_to_db(
    broker: MockBroker, cache: RedisCache, session: AsyncSession
) -> None:
    """
    Full flow: submit_order() → on_fill() → trade row readable from DB.
    """
    order_manager = OrderManager(broker, RiskManager())
    trade_handler = TradeHandler(cache)
    req = _valid_request()

    validation, order_result = await order_manager.submit_order(req)
    assert order_result.status == "FILLED"

    trade = await trade_handler.on_fill(req, validation, order_result, session)

    # Verify the row is readable in the same session (flushed but not committed).
    # trade.id is auto-generated by the DB — not req.trade_id.
    repo = TradeRepo(session)
    fetched = await repo.get_by_id(trade.id)

    assert fetched is not None
    assert fetched.symbol == "AAPL"
    assert fetched.entry_price == order_result.avg_fill_price
    assert fetched.stop_loss_price == req.stop_loss_price
    assert str(fetched.direction.value) == "BUY"
    # Session is rolled back after the test — row does not persist.


@pytest.mark.asyncio
async def test_on_fill_publishes_trade_event_to_redis(
    broker: MockBroker, cache: RedisCache, session: AsyncSession
) -> None:
    """
    on_fill() publishes a trade_executed event to the trade_events Redis channel.
    Intercepted by wrapping the cache.publish method.
    """
    order_manager = OrderManager(broker, RiskManager())
    trade_handler = TradeHandler(cache)
    req = _valid_request(symbol="MSFT")

    validation, order_result = await order_manager.submit_order(req)

    published: list[tuple[str, str]] = []
    original_publish = cache.publish

    async def capturing_publish(channel: str, message: str) -> None:
        published.append((channel, message))
        await original_publish(channel, message)

    cache.publish = capturing_publish  # type: ignore[method-assign]
    await trade_handler.on_fill(req, validation, order_result, session)
    cache.publish = original_publish  # type: ignore[method-assign]

    assert len(published) == 1
    channel, raw = published[0]
    assert channel == TRADE_EVENTS_CHANNEL
    event = json.loads(raw)
    assert event["event"] == "trade_executed"
    assert event["payload"]["symbol"] == "MSFT"
    assert event["payload"]["direction"] == "BUY"


# ---------------------------------------------------------------------------
# Rejection before any DB write
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_risk_rejection_writes_no_db_row(
    broker: MockBroker, session: AsyncSession
) -> None:
    """
    A rejected trade must leave zero rows in the DB for that trade_id.
    """
    order_manager = OrderManager(broker, RiskManager())
    req = _valid_request(stop_loss_price=None)

    with pytest.raises(RiskRejectionError):
        await order_manager.submit_order(req)

    repo = TradeRepo(session)
    fetched = await repo.get_by_id(req.trade_id)
    assert fetched is None, "Rejected trade should not appear in DB"
